CREATE SEQUENCE IF NOT EXISTS employee_sequence start
WITH
  1 increment by 1;

CREATE SEQUENCE IF NOT EXISTS address_sequence start
WITH
  1 increment by 1;

CREATE SEQUENCE IF NOT EXISTS project_sequence start
WITH
  1 increment by 1;

CREATE SEQUENCE IF NOT EXISTS department_sequence start
WITH
  1 increment by 1;

CREATE TABLE address (
  created TIMESTAMP(6) WITH TIME ZONE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  city VARCHAR(255),
  country VARCHAR(255),
  postal_code VARCHAR(255),
  state VARCHAR(255),
  street VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE department (
  created TIMESTAMP(6) WITH TIME ZONE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  code VARCHAR(255),
  name VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT department_code_index UNIQUE (code)
);

CREATE TABLE employee (
  address_id BIGINT UNIQUE,
  created TIMESTAMP(6) WITH TIME ZONE,
  department_id BIGINT,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  email VARCHAR(255),
  name VARCHAR(255),
  phone_number VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT employee_email_index UNIQUE (email)
);

CREATE TABLE employee_projects (
  employees_id BIGINT NOT NULL,
  projects_id BIGINT NOT NULL
);

CREATE TABLE project (
  created TIMESTAMP(6) WITH TIME ZONE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  code VARCHAR(255),
  name VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT project_code_index UNIQUE (code)
);

ALTER TABLE IF EXISTS employee
ADD CONSTRAINT fk_employee_address FOREIGN key (address_id) REFERENCES address;

ALTER TABLE IF EXISTS employee
ADD CONSTRAINT fk_employee_department FOREIGN key (department_id) REFERENCES department;

ALTER TABLE IF EXISTS employee_projects
ADD CONSTRAINT fk_employee_projects_project FOREIGN key (projects_id) REFERENCES project;

ALTER TABLE IF EXISTS employee_projects
ADD CONSTRAINT fk_employee_projects_employee FOREIGN key (employees_id) REFERENCES employee;
