spring:
  application:
  name: sb-template
  docker:
    compose:
      enabled: false
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      default_schema: sb_template
      ddl-auto: none
      naming:
        physical-strategy:threads: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    #temp
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: schema.sql
            create-source: metadata
    ##
  threads:
    virtual:
      enabled: true
  liquibase:
    default-schema: db_template
