name: Pull request action with Gradle

on:
  pull_request:
    branches:
      - "main"


jobs:
  build:
    permissions:
      contents: read
    uses:
      ./.github/workflows/build-gradle.yaml
    secrets: inherit
